### ISSUE TITLE
[QA]  Header 

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#111]
Bom dia!
Considerando o figma : https://www.figma.com/file/Sy3uTts6OOlrMtnhWYrRla/Pipoca-%C3%81gil---Grupo-Marrom-(Copy)?type=design&node-id=1695-4277&mode=design&t=geeKqFLfKG6Z69fa-0

1. Logo está mais a esquerda no figma
2. Falta link para página de criadores e fale com a gente
3. Quero mentorar está como botão a direita com o botão quero me voluntariar
4. Está sem ícone de redes sociais
5. Menu hamburguer está sobreponto a logo. 
6. Logo está com borda
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/ed8b587d-3237-4708-b4c3-8adfec43620c)
7. Quero mentorar está levando para página de inscrição de pessoa voluntária. 
No figma é inscrição de pessoa mentora 
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/a7269a22-7d38-4bf3-b778-c60f6e35d3ce)

Header

Figma
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/fef78b8a-6114-4da1-b084-02294b2e6626)

Site
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/1a955749-1191-4833-9500-523be205be0e)

Obrigada

**Comment by Gabrielle177** [comment]
![image](https://github.com/time-marrom/pipoca-agil-client/assets/112728574/bbc17200-8a6e-4467-8dd0-8d4633a97808)
@annagrl @LuyKarol14 
https://pipoca-agil.netlify.app/

**Comment by LuyKarol14** [comment]
Veificado, ok!
