### ISSUE TITLE
[QA] Posso me inscrever?

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#118]
Bom dia!
No figma consta como : **programador front e/ou back-end** e **PO**
No site está como **desenvolvedores** e **PO/PM**

Figma

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/03f43b49-1478-4e00-be86-02a8813b3820)

Site

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/694167b4-e8f0-4dc8-8a38-751a482601a1)
Obrigada

**Comment by annagrl** [comment]
Boa noite pessoal, divergencia de texto ainda permanece:
No site
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/ead9045a-9e01-4ea9-b5cf-8447d51cc03f)

No firma
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/722f030a-4a68-4e5c-a856-c3141e4b4ecc)


Obrigada

**Comment by annagrl** [comment]
Texto ainda está com informação de texto diferente.
No figma consta como : programador front e/ou back-end e PO
No site está como desenvolvedores e PO/PM
 ![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/b3b45bff-1e37-4bd2-ac30-eeb37738073e)

**Comment by Gabrielle177** [comment]
@annagrl @LuyKarol14 feito!
