### ISSUE TITLE
[QA] Botão Quero mentorar no componente Posso me inscrever?

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#122]
Boa noite,
Alterar de Quero mentorar um time para Quero Mentorar, pois alinhamos que está aberto caso queiram mentorar uma função específica. 

Figma
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/793291e5-d49f-4b8b-bda2-ce06a6b0a683)

Site
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/14c49f07-fc64-43b0-815c-0e6a8dd28002)

Obrigada

**Comment by Gabrielle177** [comment]
@annagrl  @LuyKarol14 @emersonjesuz feito!

**Comment by LuyKarol14** [comment]
Revisado, ok!
