### ISSUE TITLE
[QA] Footer

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#128]
Boa tarde pessoal,
Segue revisão do footer:
1. Ícones de rede social a esquerda 
2. Acesso a **Quero mentorar** e **Quero Voluntariar** 
 
 Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/fa973900-b42e-4eca-b5bf-b12bdb965048)

Figma:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/a099056e-d34b-476d-84c4-749ba2674a19)

Obrigada

**Comment by annagrl** [comment]
Segue solicitação da equipe: Footer: ícones deverão estar do lado desquerdo da pág.

**Comment by annagrl** [comment]
Boa tarde, footer ainda necessita de ajuste. Obrigada
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/b5ac82d9-b986-4a61-a9cb-959eeec7e0cd)

**Comment by pauloruan** [comment]
@annagrl @LuyKarol14 

![ok](https://media1.tenor.com/m/tLl0Bru9EdwAAAAC/thumbs-up-good-job.gif)
