### ISSUE TITLE
[QA] Página Criadores 

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#131]
Boa tarde Pessoal!
Segue ajustes na página dos criadores, por gentileza.

1. O tamanho da fonte de título/subtítulo/texto do componente dos criadores deve ser no mesmo tamanho do componente de informações do ibson.

Site:

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/dbc6be4d-99fc-4006-9c96-ea4ab729de6f)

Figma:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/354e0634-a2e4-41e2-819d-e2381d54f577)

2. Tem como diminuir esse espaço entre nome do criador e função?
Figma
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/24a4bc5f-f11d-4694-aad9-f642d1d286a1)

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/d831b1ce-f288-4d1e-84f6-54f607e07278)

Obrigada

**Comment by Gabrielle177** [comment]
essa issue foi resolvi na issue de nº 132 
branch: refactor: changes to the buttons I want to mentor
