### ISSUE TITLE
[QA] Botão Header Quero mentorar

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#132]
Olá pessoal!

1.A borda desse botão do header no site ta em 4px e no figma é 2 px. Segue abaixo:

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/41f50352-72ea-4418-a215-bafe9048220f)

Figma:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/b8d90d5e-310e-431d-8ada-053e6697a639)

2. E o botão Quero mentorar no componente "Posso me inscrever" está com background mais cinza quando ele é mais branco.
Bem sutíl mesmo a diferença. Vou tentar mostrar na foto. Mas o botão do header tá fundo certo.

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/2304fcef-bcae-4624-be47-9ef3fb86bc75)
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/adf6b31d-f641-4b88-99a8-20b9f515d575)

Figma:

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/47c1e950-0888-4362-ae96-38ec4e84a38e)

Obrigada!

**Comment by Gabrielle177** [comment]
@annagrl 
![image](https://github.com/time-marrom/pipoca-agil-client/assets/112728574/70c07000-ad06-44df-9dea-ba3af1b1d4f6)
com 2 px

![image](https://github.com/time-marrom/pipoca-agil-client/assets/112728574/ded4deb3-9af6-4680-bdd5-dde8a8893adb)
com 3 px

**Comment by Gabrielle177** [comment]
@emersonjesuz  feito!!

**Comment by LuyKarol14** [comment]
Revisado, ok!
