### ISSUE TITLE
[QA] PALAVRAS DE QUEM PARTICIPOU

### ISSUE THREAD

**Issue by LuyKarol14** [time-marrom/pipoca-agil-client#142]
Olá, Devs!

Colocar "aspas" nos textos e colocar 2 textos por pagina, segue:

Protótipo:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/133263842/4a348d02-c4b4-49a3-b039-8d2b032fb2bb)

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/133263842/e6697c7c-2ec8-4df9-b856-2fb26f157f3a)

**Comment by annagrl** [comment]
Complementando com informações passadas pela equipe :

Versão desktop da Home - Seção de depoimentos é pra ter dois depoimentos lado a lado, texto sempre alinhado à esquerda, falta as aspas roxas, botões de passar pros lados estão diferentes do protótipo também
Obrigada

**Comment by Gabrielle177** [comment]
@pauloruan @LuyKarol14 @annagrl

**Comment by annagrl** [comment]
@Gabrielle177 tava olhando no https://pipoca-agil.netlify.app/
Vi que foi adicionado as aspas, mas os ícones de seta estão diferentes e o texto está com alinhamento centralizado. 
E por último, os 2 depoimentos na tela vai ter como colocar ?
Obrigada


![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/5443762e-57eb-4f34-a04f-8132ce9cea4c)

**Comment by LuyKarol14** [comment]
Aguardando alteração @Gabrielle177 !

**Comment by Gabrielle177** [comment]
eu tbm @pauloruan

**Comment by pauloruan** [comment]
![esperando](https://media1.tenor.com/m/TFSWJKHo1LEAAAAC/waiting-patiently-on-you-i-am-bored.gif)

**Comment by Gabrielle177** [comment]
@annagrl @LuyKarol14 feito

**Comment by annagrl** [comment]
@Gabrielle177 os ícones ainda estão os antigos 

Figma 
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/590172b8-2bb9-453c-b810-32105cb5a981)
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/ddfa4c79-febc-4d8a-a3b4-080ef9e61d36)


Site
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/c848496d-e723-4ac6-92af-d46ea85c956e)
Obrigada

**Comment by annagrl** [comment]
reabrindo issue para alteração de ícone
