### ISSUE TITLE
[QA] Footer: @2024 - Links Quero mentorar e Quero me voluntariar

### ISSUE THREAD

**Issue by LuyKarol14** [time-marrom/pipoca-agil-client#145]
Olá, devs!
Alteração.
Footer: @2024 Time Marrom - todos os direitos reservados ao invés de "@2023 e retirar e-mail e nome do Ibson" Conforme protótipo.
Acrescentar link "Quero mentorar" e "Quero me voluntariar"
![image](https://github.com/time-marrom/pipoca-agil-client/assets/133263842/43ae7b62-03fa-4818-8f79-d8ee93f64611)
Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/133263842/804ef8ec-d396-44f3-9d9a-8382ad8ed85c)

**Comment by pauloruan** [comment]
@annagrl @LuyKarol14 

![ok](https://media1.tenor.com/m/tLl0Bru9EdwAAAAC/thumbs-up-good-job.gif)
