### ISSUE TITLE
[QA] Inscrição de pessoa voluntária e MENTOR - linha entre ícone 1 e 2, Inserir texto de Atenção, Alinhar título e texto centralizados

### ISSUE THREAD

**Issue by LuyKarol14** [time-marrom/pipoca-agil-client#147]
Olá devs!
Campo inscrição de pessoa voluntária, linha entre ícone 1 e 2. Inserir texto de Atenção!
Alinhar título e texto centralizados conforme protótipo:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/133263842/3fa12f59-63fc-499c-9be4-5f8bc16b2ed6)

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/133263842/7e32401a-068f-4fab-94c3-651682dd400b)

**Comment by annagrl** [comment]
Adicionando informação enviada pela equipe: Formulário quero me voluntariar -etapas da inscrição falta a linha de ligação das etapas e o espaço entre as etapas está curto

**Comment by Gabrielle177** [comment]
@LuyKarol14 @annagrl @pauloruan feito!

**Comment by LuyKarol14** [comment]
Verificado, ok!
