### ISSUE TITLE
[QA] Pág de inscrição de voluntário e MENTOR.

### ISSUE THREAD

**Issue by LuyKarol14** [time-marrom/pipoca-agil-client#148]
Olá, devs!

Corrigir: ícone e linha entre eles, inserir texto, texto voltar no campo esquerdo da pág.
Protótipo:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/133263842/57024e56-bda7-4a0f-a0af-c1b35413ecfa)

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/133263842/9c8aa617-14a4-44cc-82ba-26b4f738fe68)

**Comment by pauloruan** [comment]
Issue #161
