### ISSUE TITLE
[QA] Header versão tablet e fundo branco do componente simulação

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#151]
Boa noite!
1. Na versão tablet o header mantem os dois botões:

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/a4bf3a86-dd44-4952-bae3-416436235b99)

Figma:

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/2c02ad65-44fb-485f-8dde-16adc7cee6f8)

2. Fundo branco da imagem está maior no figma.

Obrigada

**Comment by emersonjesuz** [comment]
@pauloruan

**Comment by Gabrielle177** [comment]
@annagrl @LuyKarol14 @pauloruan feito

**Comment by annagrl** [comment]
VCS ARRASAM! vlw!!!

**Comment by annagrl** [comment]
@Gabrielle177 Na versão de ipad pro o site ta indo pro header de desktop.
e o fundo da imagem tem como 

Ipad pro
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/72fd6b7a-7ac9-4414-af00-2a83e1c9cbfa)
Ipad air
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/084239a1-47e6-4a0d-8066-a6987998478b)
Mini
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/60242822-ad09-4348-b5a3-aa66084149fb)
