### ISSUE TITLE
[QA] Pág. emissão de certificado - Corrigir texto do link VOLTAR PARA O INÍCIO

### ISSUE THREAD

**Issue by LuyKarol14** [time-marrom/pipoca-agil-client#152]
Olá devs!
Corrigir texto do link VOLTAR PARA O INÍCIO, conforme protótipo:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/133263842/cb327f85-c76c-4563-ab31-e3e0867d4d99)

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/133263842/6f6c0c38-71a9-48bf-89fe-c8324ec4d1f6)

**Comment by Gabrielle177** [comment]
resolvido
@annagrl @LuyKarol14 @pauloruan

**Comment by annagrl** [comment]
ok . Obrigada
