### ISSUE TITLE
[QA] Seta do carrossel de Palavras de quem participou na versão tablet

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#153]
Boa noite,

os ícones do carrossel estão quase saindo da tela na versão tablet, usando uma versão Air ou Mini do ipad. 

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/e364cbd2-1c83-479a-9b9a-1dbb82b77507)

Obrigada.

**Comment by Gabrielle177** [comment]
feito
@annagrl @LuyKarol14 @pauloruan

**Comment by annagrl** [comment]
Ok. Obrigada
