### ISSUE TITLE
[QA] header página de emissão de certificado e tamanho da fonte

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#154]
Boa noite!
1. Ajustar título da pagina está menor que tamanho de título

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/4de6eb37-4396-4272-99de-1682d2beedd4)

figma:

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/78c7c87a-500d-483e-b2cb-ff942a483fb7)

2. Ajustar texto de "Voltar para o início" 

3. Ajustar tamanho da fonte do helper text....ele é menor que o tamanho da fonte do label do campo

figma:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/669e8183-7f71-40c6-ad32-c67fd0431731)

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/d0ec620d-d62d-404b-8c3e-fbf90dd8f8bc)

Obrigada

**Comment by annagrl** [comment]
Complementando com informação enviada pela equipe: Emitir certificado, inscrições - inputs do formulário - rever tipografia dos helper text

**Comment by annagrl** [comment]
Oi Josi, título, ok. Texto Voltar e ícone ok.
Mas o helper texto ainda precisa dar uma olhada. Ele é mais preto que cinza

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/0b1648f8-b3d2-467b-84de-fa0a635aa204)


![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/8f25a4a5-7085-42ce-bcd6-fa1d875050e8)
Obrigada

**Comment by pauloruan** [comment]
@annagrl @LuyKarol14 

![ok](https://media1.tenor.com/m/tLl0Bru9EdwAAAAC/thumbs-up-good-job.gif)
