### ISSUE TITLE
[QA] Texto do formulário do mentor e margem

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#155]
Boa noite, **texto** está divergente nos Pré-requisitos e regras de participação da Inscrição de pessoa mentora. 

Figma:

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/d645e16e-6474-4afb-a5e3-ad5a6b752815)

" **Experiência sólida na área em que quer mentorar;**

**Disponibilidade para tirar dúvidas e orientar as pessoas voluntárias;**

Compromisso e responsabilidade com o trabalho;

Comunicação clara e frequente;

Paciência e vontade de ensinar;

Respeito com pessoas voluntárias. "

site:

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/ec828cca-47de-4e4c-a200-4dabe55a5307)

**Conhecimento teórico da área que quer atuar no projeto;**
Disponibilidade para participar frequentemente de reuniões e atividades propostas em algum turno (manhã, tarde ou noite);
Compromisso e responsabilidade com o trabalho;
Cumprir prazos de entrega de tarefas;
Trabalhar de forma colaborativa;
Disposição para aprender e compartilhar habilidades;
Respeitar pessoas da equipe;
Estar ciente de que o projeto, por ter apenas pessoas voluntárias envolvidas na sua organização e participação, poderá ser interrompido a qualquer momento.

Obrigada

**Comment by Gabrielle177** [comment]
feito 
@annagrl  @pauloruan @LuyKarol14

**Comment by annagrl** [comment]
@Gabrielle177 ao clicar em mentorar está encaminhando direto para o formulário, não está parecendo a tela de Pré-requisitos e regras de participação do mentor. 

Aparece termo de consentimento, mas já é tela de preenchimento de dados pessoais. 

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/55a21695-4495-46fa-b524-4a9c5bae2527)
Obrigada

**Comment by Gabrielle177** [comment]
@annagrl  ainda estamos mexendo no form, por isso tiramos a de aceitar o termo momentaneamente

**Comment by LuyKarol14** [comment]
Agora esta acessando normal. Verificado, ok!
