### ISSUE TITLE
[QA] Fale com a gente: adicionar os hiperlinks nos ícones

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#156]
1. Solicitação enviada pela equipe : Adicionar hiperlink aos ícones na versão desktop, mobile e tablet
Versão desktop
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/9fbc3d7f-c43f-4922-856d-556ca3978347)

Versão mobile

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/65db90bb-4e4f-4a45-84ec-13b75b1fd695)

versão tablet:

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/4f7e4453-06f2-4f7a-985f-d372e1ef8aa6)

2. Por favor, ajustar texto marcado e adicionar link. 

figma versão tablet

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/17019641-14cc-4739-a889-183c997aa07e)

Obrigada

**Comment by Gabrielle177** [comment]
feito
@annagrl @LuyKarol14 @pauloruan

**Comment by annagrl** [comment]
@Gabrielle177 verifiquei q a versão mobile e tablet ainda precisa ajustar o link para envio de email:
Tablet
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/2095a77d-2c84-4740-bb00-f6b25132e496)

Mobile
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/1a25cd60-b875-42a5-89d7-7712b6743e93)


Por gentileza, verificar alinhamento e margem do texto "Você também pode entrar em contato ..." na versão tablet. 

Figma:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/7197c71d-5d54-4c30-90fd-bbcefb82d1a7)

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/5c769520-8fe3-4231-bd6d-cf18b1642801)

Obrigada

**Comment by LuyKarol14** [comment]
Aguardando ajustes @Gabrielle177 @pauloruan 

![image](https://github.com/time-marrom/pipoca-agil-client/assets/133263842/88f0dff3-13ba-4955-842a-2a82502a0f4a)

**Comment by Gabrielle177** [comment]
@annagrl @LuyKarol14 @pauloruan ok!

**Comment by Gabrielle177** [comment]
@annagrl @LuyKarol14 @pauloruan feito!

**Comment by annagrl** [comment]
> @annagrl @LuyKarol14 @pauloruan feito!

Muito obrigada! Tudo ok!
