### ISSUE TITLE
[QA] Correção ortográfica no item: Termos e condições para participar do projeto de simulação do Pipoca Ágil> Anexo B> 9. Disponibilidade

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#158]
Olá, segue correção enviada pela equipe: daremos a oportunidade para outras pessoas que realmente queira participar; (Correção: queiram)

Nos termos e condições do voluntário:

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/7df6c7df-63c1-4dba-81aa-0f39647bfaf0)

Termos e condições do mentor

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/0187afbc-8e06-43ce-b85c-302a2f490406)

Obrigada

**Comment by Gabrielle177** [comment]
@annagrl @LuyKarol14 a uxs vão corrigir os texto pelo sanity
