### ISSUE TITLE
[QA] Correção ortográfica no item: Termos e condições para participar do projeto de simulação do Pipoca Ágil> Anexo B> 12. Compromisso com prazos

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#159]
Boa noite, segue solicitação enviada pela equipe: É importante que os membros da equipe se comprometem a entregar seu trabalho dentro dos prazos estabelecidos, para que o projeto possa avançar de forma fluida; (correção: comprometam/fluída)

no site nos termos e condições do mentor:

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/8737eb49-57ca-4e40-be47-e2f742781e6f)

no site nos termos e condições do voluntario:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/fdc0c305-5b2e-4e32-a296-2ce600b5d886)

Obrigada

**Comment by Gabrielle177** [comment]
correção ux @annagrl
