### ISSUE TITLE
[QA] Inscrição mentor - Mensagem de erro

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#160]
Boa noite , segue considerações

1. Não está dando erro ao preencher número de whatsapp

2. Verificar mensagem de erro: 
site está required nos campos: Disponibilidade de períodos (considerar horário de Brasília):/Perfil do LinkedIn/Tem alguma observação a fazer?

site :
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/b6a5e1f7-80b7-4b51-b98e-6d4b541f98bd)

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/e08964c6-eed8-4939-928e-468f4ad8c95e)

Figma:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/dbf47d03-08a7-40a1-aa64-fb8654a7de87)

3. Adicionar mensagem: **Ops! Algum campo está incorreto. Volte para cima para conferir.**

**Comment by Gabrielle177** [comment]
@pauloruan
