### ISSUE TITLE
[QA] Inscrição mentor - Modal

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#162]
Boa noite, mesmo após preenchimento da inscrição do mentor não está sendo possivel finalizar a inscrição.
Ao clicar em enviar ... não aparece o modal de conclusão

Fica assim o site

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/d212c118-3a38-40e4-bee7-193526f7686c)

Figma está com a informação q o modal de conclusão é o mesmo do voluntário
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/72709cd7-25e5-410d-be23-dfd0b5c148a0)

Obrigada

**Comment by annagrl** [comment]
Complementando com informação da equipe : Inscrição enviada com sucesso - os passos não estão de acordo (mostrar que foram concluídos)

**Comment by pauloruan** [comment]
@annagrl @LuyKarol14 

![ok](https://media1.tenor.com/m/tLl0Bru9EdwAAAAC/thumbs-up-good-job.gif)
