### ISSUE TITLE
[QA] Conclusão de formulário de contato

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#163]
Boa noite,
1. mesmo com campos preenchidos não está abrindo modal de conclusão de preenchimento do formulário

Site: Mesmo clicando em enviar....permanece nesta página
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/55fa1db7-451e-4c8c-85c9-5e253d97b095)

Modal do Figma
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/0d8b2c55-a352-4119-a6af-4d44f17a4fb6)

2. E-mail não recebido na minha caixa de entrada do teste realizado
Obrigada

**Comment by Gabrielle177** [comment]
@pauloruan

**Comment by annagrl** [comment]
Oi pessoal, formulário ainda não está sendo concluído
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/0f132227-0015-48df-b4e9-55f04a7b0e4f)
Obrigada

**Comment by annagrl** [comment]
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/9b8d15c0-4272-4f31-bc31-754e0a14c769)
N tá enviando ainda

**Comment by pauloruan** [comment]
@annagrl @LuyKarol14 

![ok](https://media1.tenor.com/m/tLl0Bru9EdwAAAAC/thumbs-up-good-job.gif)
