### ISSUE TITLE
[QA] Home - Header não está fixo no topo quando scrolla

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#165]
Olá pessoal, segue solicitação de ajuste:

Ao seguir com a página o header fica fixo....segue imagem de exemplo no figma:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/43574533-8686-4c9e-bec7-009dfb77a41e)
Obrigada

**Comment by Gabrielle177** [comment]
feito
@annagrl @LuyKarol14 @pauloruan

**Comment by annagrl** [comment]
Ok .. Obrigada
