### ISSUE TITLE
[QA] Home - Botão primário do primeiro hero - tá do mesmo tamanho do secundário, ele é pra ser maior com fonte maior tbm

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#167]
Olá,

Segue solicitação: O botão de quero me inscrever no componente simulação é maior que os botões do header. Estão do mesmo tamanho. 
Figma: Botão header com 16px e do componente com 24px de fonte
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/7f6c3529-687d-41ab-8a94-8c31ead66ca2)

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/7ffccd9b-c7b9-4399-aa23-189ce7f00257)

Obrigada

**Comment by emersonjesuz** [comment]
@pauloruan
