### ISSUE TITLE
[QA] Simulação

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#168]
olá,  enviando issue com solicitação da equipe:
solicitação: Home - Tamanhos e peso das fontes do título e texto do primeiro hero (componente) estão erradas

O título, o texto, e o botão do componente simulação devem ser maiores.
Figma:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/96ad0a3a-9d0e-41ff-b891-6bb757e5ecb7)

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/f09297b5-6701-4293-b99f-c9c959d946b8)

Obrigada!

**Comment by Gabrielle177** [comment]
feito @annagrl @LuyKarol14

**Comment by LuyKarol14** [comment]
Verificado! ok!
