### ISSUE TITLE
[QA] Home - Espaçamentos entre as seções da home tá muito grande

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#169]
Olá, segue solicitação:
Home - Espaçamentos entre as seções da home tá muito grande

Figma:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/3a767a84-01c2-4dff-97a0-2e2ed597b49e)

Site:

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/ae3fa3c4-76e2-4c80-9d7d-869cf59ab810)

Obrigada

**Comment by Gabrielle177** [comment]
feito @annagrl @LuyKarol14 @pauloruan

**Comment by annagrl** [comment]
Ok. Obrigada
