### ISSUE TITLE
[QA] Emitir certificado, inscrições - rever tipografia do título (tamanho e peso)

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#170]
Bom dia, segue solicitação:

Peso da Fonte é 500 e tamanho está em 48px. 

Figma:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/02c43667-1dda-4d95-b4a1-3be82ad31a87)

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/bd756c5d-617a-496b-bb65-b98f3b577c89)

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/850d06a1-5f9d-4fa4-95f9-a7a572de462e)
Obrigada!

**Comment by Gabrielle177** [comment]
@annagrl @LuyKarol14

**Comment by LuyKarol14** [comment]
Cotinua com 32px ao invés de 48px. Aguardando alteração.

Segue
![image](https://github.com/time-marrom/pipoca-agil-client/assets/133263842/37215fd5-554a-43c9-a8b3-b5ec0c642f8b)

**Comment by Gabrielle177** [comment]
@LuyKarol14 para mobile e para tablet no figma é 32px e para desktop apenas é para 48px, poderia me dizer qual delas deu errado?

**Comment by LuyKarol14** [comment]
@Gabrielle177 esta oK! Me perdoe pelo equivoco.

![image](https://github.com/time-marrom/pipoca-agil-client/assets/133263842/3ce90b33-2e1f-4806-a34d-762d46c2ed99)
