### ISSUE TITLE
[QA] Emitir certificado, inscrições - rever botão de voltar (falta o ícone, margem tá pequena)

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#171]
Bom dia,

Adicionar ícone de voltar e margem da borda para o botão.

Figma:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/d3bf8020-6a6a-4263-b706-c80538c955c0)

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/3c7a6762-bf6a-44f0-9847-be801ee3f514)
Obrigada

**Comment by emersonjesuz** [comment]
@pauloruan
