### ISSUE TITLE
[QA] Emitir certificado, inscrições - inputs do formulário - estão sem hover

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#172]
Bom dia, segue solicitação: 
1.Os campos estão aparecendo a borda roxa só quando selecionados. Por favor, adicionar como hoover tbm. Assim quando passar o mouse por cima, aparecer a borda.
2. Ajustar border-width. É de 1px...no site está com 2px.

Figma:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/4b0bd7b2-e9f3-4e0a-947d-b020d5fedf18)

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/0fb7f6b1-9a1d-4f4e-b4d9-7b1e26416cca)

Obrigada

**Comment by Gabrielle177** [comment]
@pauloruan

**Comment by pauloruan** [comment]
@annagrl @LuyKarol14 

![ok](https://media1.tenor.com/m/tLl0Bru9EdwAAAAC/thumbs-up-good-job.gif)
