### ISSUE TITLE
[QA] Home - Todos os botões - cor do hover tá escuro, é pra ser o roxo mais claro

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#173]
Olá, segue solicitação de ajuste:
Por favor, alterar a cor do hoover nos botões para : hex #9747FF

Segue abaixo modelo:
Figma:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/63cbb91c-8367-43a5-8bdd-946756ab92b0)

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/4982b228-0185-44d9-b674-44061828a165)
Obrigada

**Comment by Gabrielle177** [comment]
@LuyKarol14 @annagrl feito
