### ISSUE TITLE
[QA] Home - Altura do primeiro hero - tá menor

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#175]
Olá pessoal, vou registrar aqui os apontamentos de estática do site. Porém, conforme conversamos a transcrição do figma para o site não é exata devido aos diferentes tamanhos de telas.
Sendo assim, ficou combinado de buscar o ajuste que se adeque de maneira mais fiel.

Solicitação: Home - height do primeiro componente está menor

Figma:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/70844df8-329b-4c86-a06d-252f161c9f31)

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/0573cead-c818-4798-aeec-89fd782ef2f4)

Obrigada

**Comment by Gabrielle177** [comment]
@annagrl @LuyKarol14 feito

**Comment by LuyKarol14** [comment]
Verificado, ok!
