### ISSUE TITLE
[QA] Home - Texto do primeiro hero não vai até o final da margem

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#176]
Olá pessoal, vou registrar aqui os apontamentos de estática do site. Porém, conforme conversamos a transcrição do figma para o site não é exata devido aos diferentes tamanhos de telas.
Sendo assim, ficou combinado de buscar o ajuste que se adeque de maneira mais fiel.

Solicitação: Ajustar Tamanho de título e de texto do primeiro componente. No site estão menores, e no protótipo ele ocupam mais espaço na tela.

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/f2b7f8a9-542a-4c15-84d4-d59cad53aaf5)

Figma:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/9cbede79-e082-4b8b-8a7d-c63b3b772470)

Obrigada

**Comment by Gabrielle177** [comment]
ok
@annagrl @pauloruan @LuyKarol14
