### ISSUE TITLE
[QA] Home - FAQ - border radius das perguntas tá menor, tipografia tá diferente (fonte, e tamanho), não é pra ter sombreamento, tamanho da seta pra baixo tá menor

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#178]
Olá pessoal, vou registrar aqui os apontamentos de estética do site. Porém, conforme conversamos a transcrição do figma para o site não é exata devido aos diferentes tamanhos de telas.
Sendo assim, ficou combinado de buscar o ajuste que se adeque de maneira mais fiel.

Solicitação: FAQ - border radius das perguntas tá menor, tipografia tá diferente (fonte, e tamanho), não é pra ter sombreamento, tamanho da seta pra baixo tá menor

Bom border radius está um pouco menor, bem como o tamanho do campo e assim sendo o texto também e o ícone para abertura da pergunta. Por favor, teria como aumentar? Obrigada

Figma:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/f01c9356-3326-47b3-a756-48f4f4b2ee2f)

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/dafcd0b3-b9f3-42d7-87d9-349c7071e899)

**Comment by Gabrielle177** [comment]
corrigido 
@annagrl @pauloruan @LuyKarol14

**Comment by LuyKarol14** [comment]
Verificado, ok!
