### ISSUE TITLE
[QA] Home - FAQ - perguntas abertas - margem do componente tá pequena, border radius do botão "sim" tá pequena, tipografia "essa informação te ajudou?" tá errada

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#179]
Olá pessoal, vou registrar aqui os apontamentos de estática do site. Porém, conforme conversamos a transcrição do figma para o site não é exata devido aos diferentes tamanhos de telas.
Sendo assim, ficou combinado de buscar o ajuste que se adeque de maneira mais fiel.

Solicitação:  Home - FAQ - perguntas abertas - margem do componente tá pequena, border radius do botão "sim" tá pequena, tipografia "essa informação te ajudou?" tá errada

Identifiquei a o o **border radius** está menor no botão Sim, a fonte do texto "**essa informação te ajudou?**" está correta porém a letra precisa estar com um tamanho um pouco menor q o texto de resposta e em negrito (mais pesada um pouco) .
E por fim, se puder ajustar a margem do texto interno e a borda da caixa de pergunta.
Obrigada.

Figma:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/1d325e74-096a-42c6-beed-6c8b2a4b13ca)

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/42f280ad-41ee-4ba5-8c82-952a5598525f)

**Comment by Gabrielle177** [comment]
@annagrl @LuyKarol14 feito

**Comment by LuyKarol14** [comment]
@Gabrielle177 A borda do "sim' continua retangular, o tamanho da caixa de perguntas foi alterado? Na minha percepção continua menor. Aguardando alterações. Obrigada!
