### ISSUE TITLE
[QA] Footer - Verificar altura, peso das fontes, redes sociais pro outro lado, ícone do instagram é pra ser filled pra manter o padrão dos outros

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#180]
Olá, segue solicitação: Footer - Alterar altura, peso das fontes, redes sociais pro outro lado, ícone do instagram é pra ser filled pra manter o padrão dos outros

Por favor, ajustar:
1. Ajustar fonte (open sans) e texto do texto Siga Pipoca ágil (alterar para siga pipoca ágil nas redes sociais)
2. Ajustar Weight para 500 nos textos (Início/Sobre os criadores/Emitir certificado e demais)
3.Redes sociais para esquerda
4. Ícone do Instagram filled
Obrigada

Figma:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/06c36ee3-fad1-4952-abdb-1262d6e67034)

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/4d8ff3e3-73dc-4060-b88a-83344275dfbb)

**Comment by pauloruan** [comment]
@annagrl @LuyKarol14 

![ok](https://media1.tenor.com/m/tLl0Bru9EdwAAAAC/thumbs-up-good-job.gif)
