### ISSUE TITLE
[QA] Footer - botões de redes sociais estão sem hover

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#181]
Olá, por favor adicionar hoover nos botões das redes sociais.
Há alteração de cor para hex #9747FF
Obrigada

Figma
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/e27b291f-595f-4a55-9c0e-4c207b5bd7bd)

Site
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/001fa547-28a8-4571-932c-0629570ba2b8)

**Comment by pauloruan** [comment]
@annagrl @LuyKarol14 

![ok](https://media1.tenor.com/m/tLl0Bru9EdwAAAAC/thumbs-up-good-job.gif)
