### ISSUE TITLE
[QA] Header

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#182]
Olá, após a implementação do header fixo ....o mesmo está sobrepondo o próximo componente

Exemplo do site:

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/2c642f5b-3ee4-4756-ae3a-049de187a26c)

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/b72ca296-2750-4927-b126-f095f244ad98)

Obrigada

**Comment by Gabrielle177** [comment]
@annagrl @LuyKarol14 feito
