### ISSUE TITLE
[QA] Sobre os criadores - nossos cards - tamanho das fontes estão maiores, tamanhos dos ícones estão inconsistentes (manter padrão 24px), não é pra ter sombreamento

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#184]
Olá pessoal, vou registrar aqui os apontamentos de estática do site. Porém, conforme conversamos a transcrição do figma para o site não é exata devido aos diferentes tamanhos de telas.
Sendo assim, ficou combinado de buscar o ajuste que se adeque de maneira mais fiel.

Solicitação:  Sobre os criadores - nossos cards - tamanho das fontes estão maiores, tamanhos dos ícones estão inconsistentes (manter padrão 24px), não é pra ter sombreamento

Acredito que esteja ajustado, caso entendam que que não há alterações. Favor encerrar. Obrigada

Site:
Sobre os criadores - nossos cards - tamanho das fontes estão maiores, tamanhos dos ícones estão inconsistentes (manter padrão 24px), não é pra ter sombreamento

Figma:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/0a15ceee-f52c-475f-a764-fcef455cd911)

**Comment by Gabrielle177** [comment]
feito
@annagrl @pauloruan @LuyKarol14
