### ISSUE TITLE
[QA] Emitir certificado, inscrições - rever alinhamentos e limite de largura das seções de texto e formulários

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#186]
Olá pessoal, vou registrar aqui os apontamentos de estática do site. Porém, conforme conversamos a transcrição do figma para o site não é exata devido aos diferentes tamanhos de telas.
Sendo assim, ficou combinado de buscar o ajuste que se adeque de maneira mais fiel.

Solicitação:Emitir certificado, inscrições - rever alinhamentos e limite de largura das seções de texto e formulários

Obrigada

figma
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/73efe4bc-ea33-4271-b186-cf967f25695e)
Site
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/8473e752-a005-463d-b82c-30ad4c36c0f7)

**Comment by pauloruan** [comment]
@annagrl @LuyKarol14 

![ok](https://media1.tenor.com/m/tLl0Bru9EdwAAAAC/thumbs-up-good-job.gif)
