### ISSUE TITLE
[QA] Campo do formulário sem borda

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#187]
Olá pessoal, na emissão de certificado o campo está sem borda.
Obrigada

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/f2996e9e-db05-49de-afb9-b87cc6bddba8)

**Comment by annagrl** [comment]
oi Pessoal, formulário ainda com campo sem borda
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/fb7d6bcb-3152-485f-a956-664c8b35fbb4)
Obrigada

**Comment by annagrl** [comment]
Não sei se estão ajustando ainda, caso sim...favor desconsiderar. Caso não...por gentileza, verificar que as bordas estão diferentes. Obrigada

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/98edaaec-84b9-425c-a99d-caf90758b9ec)

**Comment by Gabrielle177** [comment]
@annagrl @LuyKarol14 feito!
