### ISSUE TITLE
[QA] Fale com a gente - ícone do instagram, mesma coisa (filled) e falta o hover desses botões de rede social

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#189]
Olá, por favor adicionar hoover nos botões das redes sociais.
Há alteração de cor para hex #9747FF
E alterar ícone do instagram para filled

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/b2ed2630-27b2-4925-9da5-a810fc0847ec)

Obrigada

**Comment by Gabrielle177** [comment]
ok! 
@annagrl @pauloruan @LuyKarol14

**Comment by LuyKarol14** [comment]
Revisado!
