### ISSUE TITLE
[QA] Fale com a gente - peso do título é pra ser menor

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#190]
Olá, alterar Font Weight 500 do título . Obrigada

Figma
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/cdfd03e5-5b84-4fa4-ab01-00dfce12c8ab)

Site

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/b8ea6f86-9a39-4c6e-bb83-a7fd49ba857f)

**Comment by Gabrielle177** [comment]
feito @annagrl @pauloruan @LuyKarol14

**Comment by LuyKarol14** [comment]
Revisado!
