### ISSUE TITLE
[QA] Modal termo - design precisa ser mais largo, outro border radius, com a parte dos botões fixa aparecendo - ver protótipo

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#192]
Olá, por gentileza, ajustar tamanho do termo na tela desktop.
E adicionar os botões, não só após a rolagem até o final. Obrigada

Site:

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/b3c683e1-13d6-423e-b39a-08243ccc1a6c)

Figma

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/c82b38ef-055d-41ed-8459-9d9ac2030ea1)

**Comment by Gabrielle177** [comment]
@annagrl @LuyKarol14 @pauloruan feito

**Comment by LuyKarol14** [comment]
@Gabrielle177 os botões ainda não aparecem, gentileza tirar a trasnparencia do fundo da caixa do termo. Aguardadno alterações, obrigada!
