### ISSUE TITLE
[QA] Modal termo - dar um espaçamento de 8px entre os botões

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#193]
Por favor, aumentar espaço entre os botões. Obrigada

Site:

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/0130a6ed-d439-4c52-bcc9-fd6c00a17bb6)

Figma
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/4980fd8a-cde1-4e5c-8233-c4cffa5883b5)

**Comment by Gabrielle177** [comment]
feito @annagrl @pauloruan @LuyKarol14

**Comment by annagrl** [comment]
Bom dia, segue registro da alteração. Obrigada

Desktop
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/80785711-e919-4fb5-9c1e-77a34f6c199f)

Tablet
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/4b6fc93e-1e22-4124-9f09-40b7ff4a502c)


Mobile
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/c1b02f5d-91bc-46dd-bb90-b91512d170ce)
