### ISSUE TITLE
[QA] Passos das inscrições - deixei uma outra opção no figma à direita da parte de "mentorar" caso a que a gente fez tenha ficado muito complexa :)

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#194]
Boa tarde, segue solicitação para verificação do passo a passo da inscrição do mentor:

1.No momento está sem o termo de conscentimento.
2. O layout está ajustado mas a cor ainda precisa alterar. 
Obrigada

Solicitação:
Passos das inscrições - deixei uma outra opção no figma à direita da parte de "mentorar" caso a que a gente fez tenha ficado muito complexa :)

Figma
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/18804570-1320-43c7-9f01-424f3868113a)

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/f870de84-041a-4f9b-8ba7-aaa11ccb2530)

Nova opção do figma sugerida 

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/1ffce4a9-e82c-4645-ac4b-324b9c4a5572)

Site
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/8d872386-3c35-447d-b7af-6a39413224f7)

**Comment by annagrl** [comment]
Olá pessoal, por favor segui mesmo padrão para o passo a passo da inscrição do **voluntário**.
Segue complemento enviado pela equipe: Formulário quero me voluntariar - adicionar o check a primeira etapa ao passar pra 2

Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/48363bda-f9db-4ab0-b3c0-9f160abdacf9)


Figma
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/f602918c-e6a4-4b6b-81cf-8598dff5a040)
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/5451b141-1115-4f2c-918c-046e6939eea1)
Obrigada

**Comment by Gabrielle177** [comment]
@pauloruan
