### ISSUE TITLE
[QA] Formulário de voluntariado - Aviso de Atenção

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#196]
Bom dia, está faltando o aviso " Atenção! É importante estar ciente que a inscrição  no Simulação não garante a sua participação. Isso dependerá de vagas disponíveis nos grupos." 

Figma
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/f503d939-92e2-4d18-8119-017c73364bcb)

Site
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/a1abfb9e-5316-4756-8c1d-4ba7ac5d1192)

Obrigada

**Comment by annagrl** [comment]
complementando com informação enviada pela equipe: Formulário quero me voluntariar - adicionar caixa de atenção no topo

**Comment by Gabrielle177** [comment]
![image](https://github.com/time-marrom/pipoca-agil-client/assets/112728574/efaf6ee2-5a3f-4f23-af0c-f60aef25c1d6)
@annagrl @LuyKarol14 @pauloruan  feito!

**Comment by LuyKarol14** [comment]
Observei que no QUERO MENTORAR não existe essa caixa de Atenção nem no Figma e nem no protótipo, acho que ficou sem sentido ne?! Não acham que deveria incluí-la? @annagrl @Gabrielle177

**Comment by annagrl** [comment]
Oi @LuyKarol14 Acho que para essa alteração teria que verificar antes com a equipe de UX. Pois elas saberiam dizer pq um tem a caixa e outro não.
