### ISSUE TITLE
[QA] Texto de pré requisitos do voluntário 

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#197]
Bom dia,

Pessoal está faltando o texto de "Comunicação clara e frequente com o time"

Protótipo

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/3ff1dec6-e478-4778-9f22-2a1e81624705)

Site

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/30986baf-d044-47bc-a25b-21b4ad815e81)

Obrigada

**Comment by Gabrielle177** [comment]
@annagrl @LuyKarol14 feito!

**Comment by LuyKarol14** [comment]
Verificado, ok!
