### ISSUE TITLE
[QA] Ícone Voltar - Formulário do voluntário versão mobile

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#198]
Bom dia, está faltando o ícone de voltar (seta)

Figma
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/0f071ec3-a5ab-45b7-b430-93761b2b2e42)

Site
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/ea91fec0-6c3b-4856-a6bd-f4500579d2a6)

Obrigada

**Comment by Gabrielle177** [comment]
feito
@annagrl  @pauloruan  @LuyKarol14

**Comment by LuyKarol14** [comment]
Aproveitando falta a linha ligando os ícones 1 e 2 da página de inscrição de voluntários.

![image](https://github.com/time-marrom/pipoca-agil-client/assets/133263842/6b15fbb2-3126-4469-942f-f8fd20e122ed)

Obrigada!

**Comment by LuyKarol14** [comment]
Verificado, ok!
