### ISSUE TITLE
[QA] Formulário de mentor 

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#199]
Bom dia, no formulario do mentor o campo "Tem alguma observação a fazer?" está como campo obrigatório. Única mensagem de erro para o campo é para caso ultrapasse 500 caracteres. 

Site mobile:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/fd5bb558-dc98-468d-84bc-650121ead9e3)

Site desktop
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/d957bfae-c63d-417e-9bdd-da3e2c61dcef)

Figma
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/f0560f90-da7d-4852-94e5-8e2128ab71c9)
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/5be01060-4adf-4bb5-a5bc-24f4ec649a5d)

Obrigada

**Comment by Gabrielle177** [comment]
corrigido
@annagrl  @pauloruan

**Comment by annagrl** [comment]
@Gabrielle177 o campo não é obrigatório...mas antes estava obrigatório [mesmo sem o aviso]. Mas, não é pra ser obrigatório não.  O único erro que deve mostrar é caso passe dos 500 caracteres. 

Site
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/f9c602db-4328-4033-8bbb-06bd6570ceb3)

figma
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/f126efef-6ef7-4858-98b7-dcd6dd82faad)

**Comment by annagrl** [comment]
@Gabrielle177  Tentei testar mas o formulário tá dando erro. Parece q não está mais obrigatório, então teria só que tirar o * da pergunta. Obrigada

Formulário do voluntário 
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/9b8ba214-fdd8-4745-ba80-2d04b3ac114d)
Formulário do mentor
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/8a8fb9be-ffb7-4744-bc49-8f62765bc37a)
