### ISSUE TITLE
[QA] Pop up termo de consentimento - ao clicar no checkbox o botão "continuar" deve ficar na cor roxa pra indicar que está habilitado

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#202]
Segue solicitação: Pop up termo de consentimento - ao clicar no checkbox o botão "continuar" deve ficar na cor roxa pra indicar que está habilitado

Site
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/0abcec36-f414-4c55-a967-efef8cb222ba)

Figma
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/55636916-ab54-4735-aa10-7f244556275f)

Obrigada

**Comment by Gabrielle177** [comment]
corrigido 
@annagrl  @pauloruan

**Comment by annagrl** [comment]
Vlw! 
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/472e797d-c513-43c0-afbc-c657a275291a)
