### ISSUE TITLE
[QA] Botão quero mentorar - letra minúscula na palavra "mentorar" assim como o quero voluntariar

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#203]
Boa tarde, favor modificar para letra minúscula o botão de **Quero mentorar** do header. 
no site está Quero Mentorar, no figma é Quero mentorar. 
Site:
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/7f4061db-e885-43fa-b97a-926a6e2999f9)

Protótipo
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/5c172aa6-ec68-4c20-b2aa-553d15f79e9a)
Obrigada

**Comment by Gabrielle177** [comment]
feito 
@pauloruan  @annagrl  @LuyKarol14

**Comment by LuyKarol14** [comment]
Revisado!
