### ISSUE TITLE
[QA] Termo de consentimento - espaço inferior do botão acessar termo completo está muito curto

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#204]
Boa tarde, aumentar margin bottom após o botão. Obrigada

Site
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/6d3a6619-cf96-490d-8397-42a286889885)
Figma
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/1290a05a-490a-473b-b52c-8713627a7a22)

**Comment by Gabrielle177** [comment]
feito 
@annagrl @LuyKarol14 @pauloruan

**Comment by LuyKarol14** [comment]
Revisado!
