### ISSUE TITLE
{QA] Pop up termo de consentimento - a caixa está com largura pequena

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#205]
Por favor, ajustar tamanho do modal e aumentar negrito do título. 

Site
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/1717c4d3-40d8-4636-b7e9-fb06f9ec49e6)
Figma
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/9b84b9e9-d1b6-442e-85d4-d9b88f12d73b)

Obrigada

**Comment by Gabrielle177** [comment]
feito @annagrl

**Comment by annagrl** [comment]
Tudo Ok! Muito obrigada!
