### ISSUE TITLE
[QA] Formulário quero me voluntariar / mentorar - peso das fontes e tamanhos diferentes do protótipo

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#206]
Boa tarde, em ambos os formulários o tipo de fonte precisa ser ajustado.
- Fonte do Label no site está como Fredoka e protótipo é Open sans.
- Peso da Fonte no Label está maior no site que no protótipo
- helper text mais escuro no protótipo

Site
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/06a94378-6e84-47cf-9324-f527ad0e806b)

Figma

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/ca82dba4-87bd-4c07-b305-dde2a86c9c23)

Obrigada

**Comment by Gabrielle177** [comment]
corrigido
@annagrl @pauloruan
