### ISSUE TITLE
[QA] Formulário quero me voluntariar - o erro mostrado no e-mail não direciona para o fale com a gente e não tem ícone para chama atenção de pessoas com dificuldade de visão

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#207]
Boa tarde, segue considerações da equipe:
Falta opção de **Fale conosco** na mensagem de erro do email e não tem ícone para chama atenção de pessoas com dificuldade de visão

Site
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/4d45b42d-9249-4125-a22d-378b1aa5e8ec)

Protótipo
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/7e99797b-fc2f-4d4b-84ed-cbbfe8461659)

Obrigada

**Comment by Gabrielle177** [comment]
@annagrl @LuyKarol14 @pauloruan feito!

**Comment by annagrl** [comment]
oi Pessoal, ainda está enviando sem precisar preencher:
Segue imagens 

Mentor
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/865a1120-6de1-4c8c-a63b-e7032d192089)

Voluntário
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/5ad36aab-5c4c-4628-9a92-76ca40b6b7cc)
Obrigada

**Comment by annagrl** [comment]
oi Gabi, não consegui testar. Pois não ta mostrando os erros quando deixo incompleto e quanto tento concluir sem preencher pra teste. O formuláro ta sendo enviado mesmo incompleto.

Imagens
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/6ca0c71e-e4cd-40a1-ae95-ea9a1f1e990f)
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/88bf69b8-531b-4ee3-b17f-cb42bc622855)
Obrigada
