### ISSUE TITLE
[QA] Formulário quero me voluntariar - É possível deixar a cor das bordas dos inputs preencidas, roxo inves de azul?

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#208]
Boa tarde pessoal, dois pontos aqui.
1. quando digitamos o fundo do campo permanece claro. Mas quando usamos a função de preencher automáticamente. O fundo fica azul. Tem como permanecer em branco ?
2. a borda do campo deve permanecer roxa após o preenchimento da informação. Para q o usuário possa visualizar oq já foi preenchido e oq falta preencher. 

site
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/8ca1f2ff-e1b4-4f1c-a01f-6905f4e1bab2)

figma
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/74ce6503-3b92-4d0e-b7e7-8f7b7c8ceb48)

**Comment by Gabrielle177** [comment]
@annagrl @LuyKarol14 @pauloruan 
1. Esse é um comportamento padrão do navegador para dizer que a pessoa usou o autopreecher.
2. feito

**Comment by LuyKarol14** [comment]
Verificado, ok!
