### ISSUE TITLE
[QA] Borda 

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#215]
Oi pessoal, tudo bom? Aqui ta aparecendo agora uma borda no título do campo do nome do formulário do voluntário.

Site

![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/ba3d77df-0703-4b9f-a8ac-cccee2dc8853)
Obrigada

**Comment by Gabrielle177** [comment]
feito @annagrl

**Comment by annagrl** [comment]
Tudo ok! Obrigada @Gabrielle177
