### ISSUE TITLE
[QA] Erro no formulário de contato

### ISSUE THREAD

**Issue by annagrl** [time-marrom/pipoca-agil-client#217]
![image](https://github.com/time-marrom/pipoca-agil-client/assets/89113745/7bd4f2c9-7759-4e2c-b641-00e30a014c0f)

**Comment by pauloruan** [comment]
@annagrl @LuyKarol14 

![ok](https://media1.tenor.com/m/tLl0Bru9EdwAAAAC/thumbs-up-good-job.gif)
